### ISSUE TITLE
issue: Missing sets

### ISSUE THREAD

**Issue by Aviortheking** [tcgdex/cards-database#90]
_found a missing set? create a new issue or comment below_

Some sets are currently missing from the Database based on https://bulbapedia.bulbagarden.net/wiki/Pok%C3%A9mon_Trading_Card_Game#Wizards_of_the_Coast_sets

## Normal sets

- [ ] W Promotional (Base) (No longer a set ) #183 
- [x] Best of game (E-Card) #108
- [ ] Sample (E-Card)
- [ ] Poké Card Creator Pack (EX) #184
- [x] Pokémon Futsal Collection (SWSH) #107 

## Macdonald's collections

- [x] Macdonald's Collection 2011 #101
- [x] Macdonald's Collection 2012 #101
- [ ] Macdonald's Collection 2013 #102
- [x] Macdonald's Collection 2014 #101
- [x] Macdonald's Collection 2015 #101
- [x] Macdonald's Collection 2016 #101
- [x] Macdonald's Collection 2017 #101
- [x] Macdonald's Collection 2018 #101
- [ ] Macdonald's Collection 2018 French #102
- [x] Macdonald's Collection 2019 #101
- [ ] Macdonald's Collection 2019 French #102

## Trainer Kits

- [ ] DP trainer Kit (Lucario) #106 (not complete)
- [ ] DP trainer Kit (Manaphy) #106 (not complete)
- [ ] EX trainer Kit (Latias).ts #106 (not complete)
- [ ] EX trainer Kit (Latios).ts #106 (not complete)
- [ ] EX trainer Kit 2 (Ninun).ts #106 (not complete)
- [ ] EX trainer Kit 2 (Plusle).ts #106 (not complete)
- [x] HS trainer Kit (Excadrill).ts #106 
- [ ] HS trainer Kit (Gyarados).ts #106 (not complete)
- [ ] HS trainer Kit (Raichu).ts #106 (not complete)
- [x] HS trainer Kit (Zoroark).ts #106 
- [x] SM trainer Kit (Alolan Raichu).ts #106 
- [x] SM trainer Kit (Lycanroc).ts #106 
- [x] XY trainer Kit (Bisharp).ts #106 
- [x] XY trainer Kit (Latias).ts #106 
- [x] XY trainer Kit (Latios).ts #106 
- [x] XY trainer Kit (Noivern).ts #106 
- [x] XY trainer Kit (Pikachu Libre).ts #106 
- [x] XY trainer Kit (Suicune).ts #106 
- [x] XY trainer Kit (Sylveon).ts #106 
- [x] XY trainer Kit (Wigglytuff).ts  #106

**Comment by Aviortheking** [comment]
(Closing because of status page, please create new issues if you see some strange things in sets :D)
